const express=require('express'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),cors=require('cors'),fs=require('fs'),path=require('path'),{v4:uuid}=require('uuid'),initSqlJs=require('sql.js');
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'glowzw-secret-2025-change-me',DB_PATH=path.join(__dirname,'glowzw.db');
app.use(cors());app.use(express.json({limit:"10mb"}));
app.use(express.urlencoded({limit:"10mb",extended:true}));
let db;
async function initDB(){
const SQL=await initSqlJs();
if(fs.existsSync(DB_PATH)){db=new SQL.Database(fs.readFileSync(DB_PATH));console.log('📂 DB loaded');}
else{db=new SQL.Database();console.log('🆕 New DB');}
// Add profile_pic column if upgrading from older DB
try { db.run('ALTER TABLE users ADD COLUMN profile_pic TEXT'); saveDB && saveDB(); } catch(e) {}
global.saveDB=()=>{const d=db.export();fs.writeFileSync(DB_PATH,Buffer.from(d));};
db.run(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,phone TEXT,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',first_name TEXT NOT NULL,last_name TEXT NOT NULL,city TEXT DEFAULT 'Harare',is_active INTEGER DEFAULT 1,profile_pic TEXT,created_at TEXT DEFAULT(datetime('now')));CREATE TABLE IF NOT EXISTS providers(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,business_name TEXT NOT NULL,slug TEXT UNIQUE,bio TEXT,category TEXT NOT NULL,address TEXT,city TEXT DEFAULT 'Harare',phone TEXT,whatsapp_number TEXT,rating_avg REAL DEFAULT 0,rating_count INTEGER DEFAULT 0,is_approved INTEGER DEFAULT 0,is_featured INTEGER DEFAULT 0,created_at TEXT DEFAULT(datetime('now')));CREATE TABLE IF NOT EXISTS subscriptions(id TEXT PRIMARY KEY,provider_id TEXT NOT NULL,tier TEXT DEFAULT 'starter',status TEXT DEFAULT 'pending',price_usd REAL DEFAULT 25.00,started_at TEXT,expires_at TEXT,payment_method TEXT,created_at TEXT DEFAULT(datetime('now')));CREATE TABLE IF NOT EXISTS services(id TEXT PRIMARY KEY,provider_id TEXT NOT NULL,name TEXT NOT NULL,description TEXT,category TEXT NOT NULL,price_usd REAL NOT NULL,duration_mins INTEGER NOT NULL,is_active INTEGER DEFAULT 1,sort_order INTEGER DEFAULT 0,created_at TEXT DEFAULT(datetime('now')));CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,booking_ref TEXT UNIQUE NOT NULL,customer_id TEXT NOT NULL,provider_id TEXT NOT NULL,service_id TEXT NOT NULL,service_name TEXT NOT NULL,service_price_usd REAL NOT NULL,service_duration INTEGER NOT NULL,appointment_date TEXT NOT NULL,appointment_time TEXT NOT NULL,end_time TEXT NOT NULL,status TEXT DEFAULT 'pending',payment_method TEXT,customer_notes TEXT,provider_notes TEXT,confirmed_at TEXT,completed_at TEXT,cancelled_at TEXT,created_at TEXT DEFAULT(datetime('now')));CREATE TABLE IF NOT EXISTS portfolio_photos(id TEXT PRIMARY KEY,provider_id TEXT NOT NULL,image_data TEXT NOT NULL,caption TEXT,created_at TEXT DEFAULT(datetime('now')));CREATE TABLE IF NOT EXISTS reviews(id TEXT PRIMARY KEY,booking_id TEXT UNIQUE NOT NULL,customer_id TEXT NOT NULL,provider_id TEXT NOT NULL,rating INTEGER NOT NULL,comment TEXT,created_at TEXT DEFAULT(datetime('now')));`);
saveDB();
if(!dbGet('SELECT id FROM users WHERE role=?',['admin'])){
const provUserId=uuid(),provId=uuid();
dbRun('INSERT INTO users(id,email,password_hash,role,first_name,last_name)VALUES(?,?,?,?,?,?)',[uuid(),'admin@glowzw.co.zw',bcrypt.hashSync('Admin@GlowZW1!',10),'admin','GlowZW','Admin']);
dbRun('INSERT INTO users(id,email,phone,password_hash,role,first_name,last_name,city)VALUES(?,?,?,?,?,?,?,?)',[provUserId,'tatenda@lushhair.co.zw','+263771234567',bcrypt.hashSync('Provider@123!',10),'provider','Tatenda','Moyo','Harare']);
dbRun('INSERT INTO providers(id,user_id,business_name,slug,bio,category,address,city,phone,whatsapp_number,is_approved,rating_avg,rating_count)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[provId,provUserId,'Lush Hair Studio','lush-hair-studio','Premium hair studio serving Harare since 2018. Specialists in protective styles, weaves and natural hair care.','hair','14 Van Praagh Ave, Avondale','Harare','+263771234567','263771234567',1,4.9,214]);
dbRun("INSERT INTO subscriptions(id,provider_id,tier,status,price_usd,started_at,expires_at)VALUES(?,?,'starter','active',25.00,datetime('now'),datetime('now','+30 days'))",[uuid(),provId]);
[['Box Braids (Medium)','hair',35,180,0],['Full Sew-In Weave','hair',45,120,1],['Relaxer & Blowout','hair',25,90,2],['Natural Wash & Style','hair',20,60,3],['Wig Install','hair',30,75,4]].forEach(([n,c,p,d,i])=>dbRun('INSERT INTO services(id,provider_id,name,category,price_usd,duration_mins,sort_order)VALUES(?,?,?,?,?,?,?)',[uuid(),provId,n,c,p,d,i]));
const custId=uuid();
dbRun('INSERT INTO users(id,email,phone,password_hash,role,first_name,last_name)VALUES(?,?,?,?,?,?,?)',[custId,'melody@email.com','+263772000001',bcrypt.hashSync('Customer@123!',10),'customer','Melody','Chirwa']);
saveDB();
console.log('✅ Demo data seeded\n  Admin:    admin@glowzw.co.zw / Admin@GlowZW1!\n  Provider: tatenda@lushhair.co.zw / Provider@123!\n  Customer: melody@email.com / Customer@123!');
}}
function dbRun(sql,p=[]){db.run(sql,p);saveDB();}
function dbGet(sql,p=[]){const s=db.prepare(sql);s.bind(p);if(s.step()){const r=s.getAsObject();s.free();return r;}s.free();return null;}
function dbAll(sql,p=[]){const r=db.exec(sql,p);if(!r.length)return[];const{columns:c,values:v}=r[0];return v.map(row=>{const o={};c.forEach((col,i)=>o[col]=row[i]);return o;});}
const signToken=(id,role)=>jwt.sign({id,role},JWT_SECRET,{expiresIn:'7d'});
const genRef=()=>'GZW-'+Date.now().toString(36).toUpperCase().slice(-4)+Math.random().toString(36).toUpperCase().slice(2,5);
const genSlug=(n)=>n.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now().toString(36);
const calcEnd=(s,m)=>{const[h,mn]=s.split(':').map(Number),t=h*60+mn+m;return`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;};
const auth=(roles=[])=>(req,res,next)=>{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({success:false,message:'Login required'});try{const d=jwt.verify(h.split(' ')[1],JWT_SECRET);if(roles.length&&!roles.includes(d.role))return res.status(403).json({success:false,message:'Access denied'});req.user=d;next();}catch{res.status(401).json({success:false,message:'Session expired. Please login again.'});}};
app.get('/health',(req,res)=>res.json({status:'ok',service:'GlowZW API',version:'1.0.0'}));
app.get('/',(req,res)=>res.json({message:'GlowZW API running 🌟'}));
// AUTH
app.post('/api/auth/login',(req,res)=>{const{email,password}=req.body;if(!email||!password)return res.status(400).json({success:false,message:'Email and password required'});const user=dbGet(`SELECT u.*,p.id AS provider_id,p.business_name,p.is_approved,p.slug,p.category AS prov_category,s.status AS sub_status,s.tier,s.expires_at,s.price_usd AS sub_price FROM users u LEFT JOIN providers p ON p.user_id=u.id LEFT JOIN subscriptions s ON s.provider_id=p.id WHERE u.email=?`,[email]);if(!user||!bcrypt.compareSync(password,user.password_hash))return res.status(401).json({success:false,message:'Invalid email or password'});if(!user.is_active)return res.status(403).json({success:false,message:'Account suspended'});const{password_hash,...safe}=user;res.json({success:true,data:{user:safe,token:signToken(user.id,user.role)}});});
app.post('/api/auth/register',(req,res)=>{const{email,password,firstName,lastName,phone,city,role,businessName,category}=req.body;if(!email||!password||!firstName||!lastName)return res.status(400).json({success:false,message:'Required fields missing'});if(password.length<8)return res.status(400).json({success:false,message:'Password must be at least 8 characters'});if(dbGet('SELECT id FROM users WHERE email=?',[email]))return res.status(409).json({success:false,message:'Email already registered'});const userRole=['customer','provider'].includes(role)?role:'customer';const userId=uuid();dbRun('INSERT INTO users(id,email,phone,password_hash,role,first_name,last_name,city)VALUES(?,?,?,?,?,?,?,?)',[userId,email,phone||null,bcrypt.hashSync(password,10),userRole,firstName,lastName,city||'Harare']);let provId=null;if(userRole==='provider'){if(!businessName||!category)return res.status(400).json({success:false,message:'Business name and category required'});provId=uuid();dbRun('INSERT INTO providers(id,user_id,business_name,slug,category,phone,whatsapp_number)VALUES(?,?,?,?,?,?,?)',[provId,userId,businessName,genSlug(businessName),category,phone||null,phone||null]);dbRun("INSERT INTO subscriptions(id,provider_id,status,price_usd)VALUES(?,?,'pending',25.00)",[uuid(),provId]);}res.status(201).json({success:true,message:userRole==='provider'?'Registered! Pay subscription to go live.':'Welcome to GlowZW!',data:{token:signToken(userId,userRole),user:{id:userId,email,role:userRole,first_name:firstName,last_name:lastName,provider_id:provId}}});});
app.get('/api/auth/me',auth(),(req,res)=>{const u=dbGet(`SELECT u.id,u.email,u.phone,u.role,u.first_name,u.last_name,u.city,p.id AS provider_id,p.business_name,p.slug,p.is_approved,p.category,s.status AS sub_status,s.tier FROM users u LEFT JOIN providers p ON p.user_id=u.id LEFT JOIN subscriptions s ON s.provider_id=p.id WHERE u.id=?`,[req.user.id]);res.json({success:true,data:u});});
// PROVIDERS
app.get('/api/providers',(req,res)=>{const{category,city,search}=req.query;let sql=`SELECT p.*,u.first_name||' '||u.last_name AS owner_name,(SELECT MIN(price_usd) FROM services sv WHERE sv.provider_id=p.id AND sv.is_active=1) AS price_from,(SELECT COUNT(*) FROM services sv WHERE sv.provider_id=p.id AND sv.is_active=1) AS service_count FROM providers p JOIN users u ON u.id=p.user_id JOIN subscriptions s ON s.provider_id=p.id WHERE p.is_approved=1 AND s.status='active'`;const params=[];if(category){sql+=' AND p.category=?';params.push(category.toLowerCase());}if(city){sql+=' AND p.city LIKE ?';params.push('%'+city+'%');}if(search){sql+=' AND p.business_name LIKE ?';params.push('%'+search+'%');}sql+=' ORDER BY p.is_featured DESC,p.rating_avg DESC LIMIT 50';res.json({success:true,data:dbAll(sql,params)});});
app.get('/api/providers/me/dashboard',auth(['provider']),(req,res)=>{const p=dbGet('SELECT * FROM providers WHERE user_id=?',[req.user.id]);if(!p)return res.status(404).json({success:false,message:'Not found'});const sub=dbGet('SELECT * FROM subscriptions WHERE provider_id=? ORDER BY created_at DESC LIMIT 1',[p.id]);const stats=dbGet(`SELECT COUNT(*) AS bookings_this_month,COALESCE(SUM(CASE WHEN status='completed' THEN service_price_usd ELSE 0 END),0) AS revenue_this_month FROM bookings WHERE provider_id=? AND strftime('%Y-%m',appointment_date)=strftime('%Y-%m','now')`,[p.id]);const upcoming=dbAll(`SELECT b.*,u.first_name||' '||u.last_name AS customer_name,u.phone AS customer_phone FROM bookings b JOIN users u ON u.id=b.customer_id WHERE b.provider_id=? AND b.appointment_date>=date('now') AND b.status IN ('confirmed','pending') ORDER BY b.appointment_date,b.appointment_time LIMIT 15`,[p.id]);const revenueTrend=dbAll(`SELECT strftime('%b',appointment_date) AS month,COALESCE(SUM(service_price_usd),0) AS revenue FROM bookings WHERE provider_id=? AND status='completed' AND appointment_date>=date('now','-6 months') GROUP BY strftime('%Y-%m',appointment_date) ORDER BY appointment_date`,[p.id]);res.json({success:true,data:{provider:p,subscription:sub,stats,upcomingBookings:upcoming,revenueTrend}});});
app.get('/api/providers/:id/availability',(req,res)=>{const{date}=req.query;if(!date)return res.status(400).json({success:false,message:'date required'});res.json({success:true,data:{bookedSlots:dbAll(`SELECT appointment_time,end_time FROM bookings WHERE provider_id=? AND appointment_date=? AND status NOT IN ('cancelled','no_show')`,[req.params.id,date])}});});
app.get('/api/providers/:slug',(req,res)=>{const p=dbGet(`SELECT p.*,u.first_name||' '||u.last_name AS owner_name FROM providers p JOIN users u ON u.id=p.user_id WHERE(p.slug=? OR p.id=?) AND p.is_approved=1`,[req.params.slug,req.params.slug]);if(!p)return res.status(404).json({success:false,message:'Not found'});const services=dbAll('SELECT * FROM services WHERE provider_id=? AND is_active=1 ORDER BY sort_order',[p.id]);const reviews=dbAll(`SELECT r.*,u.first_name||' '||SUBSTR(u.last_name,1,1)||'.' AS customer_name FROM reviews r JOIN users u ON u.id=r.customer_id WHERE r.provider_id=? ORDER BY r.created_at DESC LIMIT 10`,[p.id]);res.json({success:true,data:{...p,services,reviews}});});
app.patch('/api/providers/me',auth(['provider']),(req,res)=>{const{bio,address,city,phone,whatsapp_number}=req.body;const p=dbGet('SELECT id FROM providers WHERE user_id=?',[req.user.id]);if(!p)return res.status(404).json({success:false,message:'Not found'});dbRun('UPDATE providers SET bio=COALESCE(?,bio),address=COALESCE(?,address),city=COALESCE(?,city),phone=COALESCE(?,phone),whatsapp_number=COALESCE(?,whatsapp_number) WHERE id=?',[bio||null,address||null,city||null,phone||null,whatsapp_number||null,p.id]);res.json({success:true,message:'Updated'});});
// SERVICES
app.get('/api/services',(req,res)=>{const{providerId,category}=req.query;let sql='SELECT s.*,p.business_name FROM services s JOIN providers p ON p.id=s.provider_id WHERE s.is_active=1';const params=[];if(providerId){sql+=' AND s.provider_id=?';params.push(providerId);}if(category){sql+=' AND s.category=?';params.push(category);}sql+=' ORDER BY s.sort_order,s.name';res.json({success:true,data:dbAll(sql,params)});});
app.post('/api/services',auth(['provider']),(req,res)=>{const p=dbGet('SELECT id FROM providers WHERE user_id=?',[req.user.id]);if(!p)return res.status(404).json({success:false,message:'Not found'});const{name,description,category,priceUsd,durationMins}=req.body;if(!name||!category||!priceUsd||!durationMins)return res.status(400).json({success:false,message:'All fields required'});const id=uuid();dbRun('INSERT INTO services(id,provider_id,name,description,category,price_usd,duration_mins)VALUES(?,?,?,?,?,?,?)',[id,p.id,name,description||null,category,priceUsd,durationMins]);res.status(201).json({success:true,data:dbGet('SELECT * FROM services WHERE id=?',[id])});});
app.patch('/api/services/:id',auth(['provider']),(req,res)=>{const p=dbGet('SELECT id FROM providers WHERE user_id=?',[req.user.id]);if(!p)return res.status(404).json({success:false,message:'Not found'});const{name,priceUsd,durationMins,isActive}=req.body;dbRun('UPDATE services SET name=COALESCE(?,name),price_usd=COALESCE(?,price_usd),duration_mins=COALESCE(?,duration_mins),is_active=COALESCE(?,is_active) WHERE id=? AND provider_id=?',[name||null,priceUsd||null,durationMins||null,isActive!=null?isActive:null,req.params.id,p.id]);res.json({success:true,message:'Updated'});});
app.delete('/api/services/:id',auth(['provider']),(req,res)=>{const p=dbGet('SELECT id FROM providers WHERE user_id=?',[req.user.id]);if(!p)return res.status(404).json({success:false,message:'Not found'});dbRun('UPDATE services SET is_active=0 WHERE id=? AND provider_id=?',[req.params.id,p.id]);res.json({success:true,message:'Removed'});});
// BOOKINGS
app.post('/api/bookings',auth(['customer']),(req,res)=>{const{serviceId,appointmentDate,appointmentTime,paymentMethod,notes}=req.body;if(!serviceId||!appointmentDate||!appointmentTime)return res.status(400).json({success:false,message:'serviceId, appointmentDate, appointmentTime required'});const svc=dbGet(`SELECT s.*,p.id AS prov_id,p.business_name,p.is_approved,sub.status AS sub_status FROM services s JOIN providers p ON p.id=s.provider_id LEFT JOIN subscriptions sub ON sub.provider_id=p.id WHERE s.id=? AND s.is_active=1`,[serviceId]);if(!svc)return res.status(404).json({success:false,message:'Service not found'});if(!svc.is_approved)return res.status(400).json({success:false,message:'Provider not active'});if(svc.sub_status!=='active')return res.status(400).json({success:false,message:'Provider subscription inactive'});const endTime=calcEnd(appointmentTime,svc.duration_mins);const conflict=dbGet(`SELECT id FROM bookings WHERE provider_id=? AND appointment_date=? AND status NOT IN ('cancelled','no_show') AND((appointment_time<=? AND end_time>?)OR(appointment_time<? AND end_time>=?)OR(appointment_time>=? AND end_time<=?))`,[svc.prov_id,appointmentDate,appointmentTime,appointmentTime,endTime,endTime,appointmentTime,endTime]);if(conflict)return res.status(409).json({success:false,message:'That time slot is already booked. Please choose another time.'});const id=uuid();dbRun(`INSERT INTO bookings(id,booking_ref,customer_id,provider_id,service_id,service_name,service_price_usd,service_duration,appointment_date,appointment_time,end_time,payment_method,customer_notes)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`,[id,genRef(),req.user.id,svc.prov_id,serviceId,svc.name,svc.price_usd,svc.duration_mins,appointmentDate,appointmentTime,endTime,paymentMethod||null,notes||null]);const booking=dbGet(`SELECT b.*,p.business_name FROM bookings b JOIN providers p ON p.id=b.provider_id WHERE b.id=?`,[id]);res.status(201).json({success:true,data:booking});});
app.get('/api/bookings/mine',auth(['customer']),(req,res)=>{res.json({success:true,data:dbAll(`SELECT b.*,p.business_name,p.whatsapp_number,p.category FROM bookings b JOIN providers p ON p.id=b.provider_id WHERE b.customer_id=? ORDER BY b.appointment_date DESC,b.appointment_time DESC`,[req.user.id])});});
app.get('/api/bookings/provider',auth(['provider']),(req,res)=>{const p=dbGet('SELECT id FROM providers WHERE user_id=?',[req.user.id]);if(!p)return res.status(404).json({success:false,message:'Not found'});const{status,date}=req.query;let sql=`SELECT b.*,u.first_name||' '||u.last_name AS customer_name,u.phone AS customer_phone FROM bookings b JOIN users u ON u.id=b.customer_id WHERE b.provider_id=?`;const params=[p.id];if(status){sql+=' AND b.status=?';params.push(status);}if(date){sql+=' AND b.appointment_date=?';params.push(date);}sql+=' ORDER BY b.appointment_date,b.appointment_time';res.json({success:true,data:dbAll(sql,params)});});
app.patch('/api/bookings/:id/status',auth(['provider','admin']),(req,res)=>{const{status,providerNotes}=req.body;if(!['confirmed','in_progress','completed','cancelled','no_show'].includes(status))return res.status(400).json({success:false,message:'Invalid status'});const b=dbGet(`SELECT b.*,p.user_id AS prov_user FROM bookings b JOIN providers p ON p.id=b.provider_id WHERE b.id=?`,[req.params.id]);if(!b)return res.status(404).json({success:false,message:'Not found'});if(req.user.role==='provider'&&b.prov_user!==req.user.id)return res.status(403).json({success:false,message:'Not your booking'});const now=new Date().toISOString();dbRun(`UPDATE bookings SET status=?,provider_notes=COALESCE(?,provider_notes),confirmed_at=CASE WHEN ?='confirmed' THEN ? ELSE confirmed_at END,completed_at=CASE WHEN ?='completed' THEN ? ELSE completed_at END,cancelled_at=CASE WHEN ?='cancelled' THEN ? ELSE cancelled_at END WHERE id=?`,[status,providerNotes||null,status,now,status,now,status,now,req.params.id]);res.json({success:true,message:'Booking '+status});});
app.post('/api/bookings/:id/review',auth(['customer']),(req,res)=>{const{rating,comment}=req.body;if(!rating||rating<1||rating>5)return res.status(400).json({success:false,message:'Rating 1-5 required'});const b=dbGet("SELECT * FROM bookings WHERE id=? AND customer_id=? AND status='completed'",[req.params.id,req.user.id]);if(!b)return res.status(404).json({success:false,message:'Completed booking not found'});if(dbGet('SELECT id FROM reviews WHERE booking_id=?',[req.params.id]))return res.status(409).json({success:false,message:'Already reviewed'});dbRun('INSERT INTO reviews(id,booking_id,customer_id,provider_id,rating,comment)VALUES(?,?,?,?,?,?)',[uuid(),req.params.id,req.user.id,b.provider_id,rating,comment||null]);const avg=dbGet('SELECT AVG(rating) AS avg,COUNT(*) AS cnt FROM reviews WHERE provider_id=?',[b.provider_id]);dbRun('UPDATE providers SET rating_avg=?,rating_count=? WHERE id=?',[avg.avg||0,avg.cnt,b.provider_id]);res.status(201).json({success:true,message:'Review submitted!'});});
// SUBSCRIPTIONS
app.get('/api/subscriptions/mine',auth(['provider']),(req,res)=>{const p=dbGet('SELECT id FROM providers WHERE user_id=?',[req.user.id]);if(!p)return res.status(404).json({success:false,message:'Not found'});res.json({success:true,data:dbGet('SELECT * FROM subscriptions WHERE provider_id=? ORDER BY created_at DESC LIMIT 1',[p.id])});});
app.get('/api/subscriptions/tiers',(req,res)=>res.json({success:true,data:[{tier:'starter',price:25,features:['Listed on GlowZW','Up to 10 services','Analytics dashboard','WhatsApp notifications','Customer reviews']},{tier:'growth',price:45,features:['Everything in Starter','Featured placement','Unlimited services','Priority support']},{tier:'premium',price:75,features:['Everything in Growth','Homepage feature','Dedicated account manager']}]}));
// ADMIN
app.get('/api/admin/dashboard',auth(['admin']),(req,res)=>{const providers=dbGet(`SELECT COUNT(*) AS total,SUM(CASE WHEN is_approved=1 THEN 1 ELSE 0 END) AS active,SUM(CASE WHEN is_approved=0 THEN 1 ELSE 0 END) AS pending FROM providers`);const bookings=dbGet(`SELECT COUNT(*) AS total,SUM(CASE WHEN status='confirmed' THEN 1 ELSE 0 END) AS confirmed,SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) AS completed FROM bookings`);const revenue=dbGet(`SELECT COUNT(*) AS active_subs,COUNT(*)*25 AS mrr_usd FROM subscriptions WHERE status='active'`);const recentProviders=dbAll(`SELECT p.*,u.email,u.first_name||' '||u.last_name AS owner_name,s.status AS sub_status FROM providers p JOIN users u ON u.id=p.user_id LEFT JOIN subscriptions s ON s.provider_id=p.id ORDER BY p.created_at DESC LIMIT 10`);const recentBookings=dbAll(`SELECT b.*,p.business_name AS provider_name,u.first_name||' '||u.last_name AS customer_name FROM bookings b JOIN providers p ON p.id=b.provider_id JOIN users u ON u.id=b.customer_id ORDER BY b.created_at DESC LIMIT 15`);res.json({success:true,data:{providers,bookings,revenue,recentProviders,recentBookings,revenueTrend:[]}});});
app.get('/api/admin/providers',auth(['admin']),(req,res)=>{const{status}=req.query;let sql=`SELECT p.*,u.email,u.phone,u.first_name||' '||u.last_name AS owner_name,s.status AS sub_status,s.tier,s.expires_at,(SELECT COUNT(*) FROM bookings b WHERE b.provider_id=p.id) AS total_bookings FROM providers p JOIN users u ON u.id=p.user_id LEFT JOIN subscriptions s ON s.provider_id=p.id`;if(status==='pending')sql+=' WHERE p.is_approved=0';if(status==='active')sql+=' WHERE p.is_approved=1';if(status==='suspended')sql+=" WHERE s.status='suspended'";sql+=' ORDER BY p.created_at DESC';res.json({success:true,data:dbAll(sql)});});
app.patch('/api/admin/providers/:id/approve',auth(['admin']),(req,res)=>{dbRun('UPDATE providers SET is_approved=1 WHERE id=?',[req.params.id]);dbRun("UPDATE subscriptions SET status='active',started_at=datetime('now'),expires_at=datetime('now','+30 days') WHERE provider_id=? AND status='pending'",[req.params.id]);res.json({success:true,message:'Provider approved'});});
app.patch('/api/admin/providers/:id/suspend',auth(['admin']),(req,res)=>{dbRun('UPDATE providers SET is_approved=0 WHERE id=?',[req.params.id]);dbRun("UPDATE subscriptions SET status='suspended' WHERE provider_id=?",[req.params.id]);res.json({success:true,message:'Provider suspended'});});
app.get('/api/admin/subscriptions',auth(['admin']),(req,res)=>res.json({success:true,data:dbAll(`SELECT s.*,p.business_name,p.category,u.email,u.phone FROM subscriptions s JOIN providers p ON p.id=s.provider_id JOIN users u ON u.id=p.user_id ORDER BY s.created_at DESC`)}));
app.post('/api/admin/subscriptions/:id/mark-paid',auth(['admin']),(req,res)=>{const{paymentMethod}=req.body;const sub=dbGet('SELECT * FROM subscriptions WHERE id=?',[req.params.id]);if(!sub)return res.status(404).json({success:false,message:'Not found'});const months=req.body.months||1;const price=req.body.customPrice||null;
  dbRun("UPDATE subscriptions SET status='active',payment_method=?,price_usd=COALESCE(?,price_usd),started_at=datetime('now'),expires_at=datetime('now','+"+(months*30)+" days') WHERE id=?",[paymentMethod||'usd_cash',price,req.params.id]);dbRun('UPDATE providers SET is_approved=1 WHERE id=?',[sub.provider_id]);res.json({success:true,message:'Activated'});});
app.get('/api/admin/analytics',auth(['admin']),(req,res)=>{const byCategory=dbAll(`SELECT p.category,COUNT(b.id) AS bookings,COALESCE(SUM(b.service_price_usd),0) AS revenue FROM bookings b JOIN providers p ON p.id=b.provider_id WHERE b.status='completed' GROUP BY p.category ORDER BY bookings DESC`);const topProviders=dbAll(`SELECT p.business_name,p.category,p.rating_avg,COUNT(b.id) AS bookings,COALESCE(SUM(b.service_price_usd),0) AS revenue FROM providers p LEFT JOIN bookings b ON b.provider_id=p.id AND b.status='completed' WHERE p.is_approved=1 GROUP BY p.id ORDER BY bookings DESC LIMIT 10`);res.json({success:true,data:{byCategory,topProviders}});});
app.get('/api/admin/users',auth(['admin']),(req,res)=>{const{role}=req.query;let sql='SELECT id,email,phone,role,first_name,last_name,city,is_active,created_at FROM users';if(role)sql+=` WHERE role='${role}'`;sql+=' ORDER BY created_at DESC';res.json({success:true,data:dbAll(sql)});});
initDB().then(()=>app.listen(PORT,()=>{console.log(`\n🌟 GlowZW API on port ${PORT}\n`);})).catch(e=>{console.error('Start failed:',e);process.exit(1);});


// DELETE /api/admin/providers/:id  - permanently remove provider
app.delete('/api/admin/providers/:id',auth(['admin']),(req,res)=>{
  const id=req.params.id;
  // Delete all related data
  dbRun('DELETE FROM portfolio_photos WHERE provider_id=?',[id]);
  dbRun('DELETE FROM reviews WHERE provider_id=?',[id]);
  dbRun('DELETE FROM bookings WHERE provider_id=?',[id]);
  dbRun('DELETE FROM services WHERE provider_id=?',[id]);
  dbRun('DELETE FROM subscriptions WHERE provider_id=?',[id]);
  const p=dbGet('SELECT user_id FROM providers WHERE id=?',[id]);
  dbRun('DELETE FROM providers WHERE id=?',[id]);
  if(p) dbRun('DELETE FROM users WHERE id=?',[p.user_id]);
  res.json({success:true,message:'Provider permanently deleted'});
});


// PATCH /api/auth/profile - update profile pic and details
app.patch('/api/auth/profile',auth(),(req,res)=>{
  const{profilePic,firstName,lastName,phone,city}=req.body;
  if(profilePic && profilePic.length > 5242880) return res.status(400).json({success:false,message:'Image too large. Max 5MB.'});
  dbRun('UPDATE users SET profile_pic=COALESCE(?,profile_pic),first_name=COALESCE(?,first_name),last_name=COALESCE(?,last_name),phone=COALESCE(?,phone),city=COALESCE(?,city) WHERE id=?',
    [profilePic||null,firstName||null,lastName||null,phone||null,city||null,req.user.id]);
  const user=dbGet('SELECT id,email,phone,role,first_name,last_name,city,profile_pic FROM users WHERE id=?',[req.user.id]);
  res.json({success:true,message:'Profile updated!',data:user});
});

// ═══════════════════════════════════════════════════════════
//  PORTFOLIO PHOTOS  (appended)
// ═══════════════════════════════════════════════════════════


// POST /api/portfolio  — provider uploads a photo (base64)
app.post('/api/portfolio', auth(['provider']), function(req, res) {
  var p = dbGet('SELECT id FROM providers WHERE user_id=?', [req.user.id]);
  if (!p) return res.status(404).json({success:false, message:'Provider not found'});
  var imageData = req.body.imageData;
  var caption = req.body.caption || '';
  if (!imageData) return res.status(400).json({success:false, message:'imageData required'});
  // Limit to 5 photos per provider
  var count = dbGet('SELECT COUNT(*) AS cnt FROM portfolio_photos WHERE provider_id=?', [p.id]);
  if (count && count.cnt >= 5) return res.status(400).json({success:false, message:'Maximum 5 portfolio photos allowed'});
  var id = uuid();
  dbRun('INSERT INTO portfolio_photos (id,provider_id,image_data,caption) VALUES (?,?,?,?)', [id, p.id, imageData, caption]);
  res.status(201).json({success:true, message:'Photo uploaded!', data:{id:id}});
});

// GET /api/portfolio/:providerId  — public, get all photos for a provider
app.get('/api/portfolio/:providerId', function(req, res) {
  var photos = dbAll('SELECT id,caption,image_data,created_at FROM portfolio_photos WHERE provider_id=? ORDER BY created_at DESC', [req.params.providerId]);
  res.json({success:true, data:photos});
});

// DELETE /api/portfolio/:id  — provider deletes their photo
app.delete('/api/portfolio/:id', auth(['provider']), function(req, res) {
  var p = dbGet('SELECT id FROM providers WHERE user_id=?', [req.user.id]);
  if (!p) return res.status(404).json({success:false, message:'Not found'});
  dbRun('DELETE FROM portfolio_photos WHERE id=? AND provider_id=?', [req.params.id, p.id]);
  res.json({success:true, message:'Photo removed'});
});
